import { z } from 'zod';

export const communitySchema = z.object({
  name: z.string().max(64),
  fit: z.string().max(120),
  note: z.string().max(180),
  strictness: z.enum(['low', 'medium', 'high']).optional(),
  badges: z.array(z.enum([
    'beginner-friendly',
    'strict-moderation',
    'megathread-first',
    'fast-responses',
    'portfolio-required',
    'learning-safe',
    'founder-focused',
  ])).optional(),
  requires: z.array(z.string().max(60)).max(4).optional(),
  avoidIf: z.array(z.string().max(60)).max(4).optional(),
});

export const routeCategorySchema = z.object({
  id: z.string().min(1).max(80),
  title: z.string().max(60),
  description: z.string().max(180),
  marker: z.string().min(1).max(4),
  accent: z.string().min(1).max(100),
  enabled: z.boolean(),
  expanded: z.boolean(),
  communities: z.array(communitySchema).max(5),
  tips: z.array(z.string().max(100)).max(6),
  warning: z.string().max(180),
  path: z.string().max(180),
});

export const routeCategoriesSchema = z.array(routeCategorySchema).max(30);

export const analyticsSchema = z.object({
  categoryClicks: z.record(z.string(), z.number()),
  destinationClicks: z.record(z.string(), z.number()),
  recentActivity: z.array(z.string()).max(8),
  totalCategoryClicks: z.number(),
  totalDestinationClicks: z.number(),
  preventedMisroutes: z.number().optional(),
  reducedRepetitiveQuestions: z.number().optional(),
  moderationEfficiencyGain: z.number().optional(),
});

export type Community = z.infer<typeof communitySchema>;
export type RouteCategory = z.infer<typeof routeCategorySchema>;
export type RouterAnalytics = z.infer<typeof analyticsSchema>;

export const defaultCategories: RouteCategory[] = [
  {
    id: 'find-work',
    title: 'Find Work',
    description: 'Route to opportunity spaces before posting.',
    marker: 'FW',
    accent: 'from-orange-300/36 via-amber-300/14 to-transparent',
    enabled: true,
    expanded: true,
    communities: [
      {
        name: 'r/forhire',
        fit: 'Best for experienced freelancers',
        note: 'Use when the user has portfolio proof and clear pricing.',
        strictness: 'high',
        badges: ['portfolio-required', 'strict-moderation'],
        requires: ['Portfolio link or examples', 'Pricing or rate range', 'Clear scope of work'],
        avoidIf: ['First-time freelancer without examples', 'Vague project description', 'No rate information'],
      },
      {
        name: 'r/remotework',
        fit: 'Remote-first opportunities',
        note: 'Good for users asking where to find distributed work.',
        strictness: 'medium',
        badges: ['beginner-friendly', 'fast-responses'],
        requires: ['Experience level specified', 'Time zone mentioned'],
        avoidIf: ['Generic job search posts', 'Requests for job boards'],
      },
      {
        name: 'r/slavelabour',
        fit: 'Beginner-friendly quick gigs',
        note: 'Warn users to read pay rules and post quality expectations.',
        strictness: 'medium',
        badges: ['beginner-friendly', 'fast-responses'],
        requires: ['Clear description of task', 'Budget range'],
        avoidIf: ['Complex development projects', 'Permanent positions'],
      },
    ],
    tips: ['Add portfolio', 'Mention timezone', 'Include pricing'],
    warning: 'Low effort posts may be removed by community moderators.',
    path: 'Intent > Experience level > Portfolio readiness > Posting rules',
  },
  {
    id: 'hire-talent',
    title: 'Hire Talent',
    description: 'Shape hiring intent before users create requests.',
    marker: 'HT',
    accent: 'from-sky-300/30 via-cyan-300/10 to-transparent',
    enabled: true,
    expanded: false,
    communities: [
      {
        name: 'r/forhire',
        fit: 'Contractors and freelancers',
        note: 'Best when budget, scope, and timeline are already clear.',
        strictness: 'high',
        badges: ['strict-moderation', 'fast-responses'],
        requires: ['Budget range specified', 'Clear project scope', 'Timeline expectations'],
        avoidIf: ['No budget mentioned', 'Vague requirements', 'Reverse recruiting'],
      },
      {
        name: 'r/webdev',
        fit: 'Technical feedback before hiring',
        note: 'Useful when users need scope review before a hiring post.',
        strictness: 'medium',
        badges: ['beginner-friendly'],
        requires: ['Technical details', 'Project background'],
        avoidIf: ['Off-topic hiring', 'Sales pitches'],
      },
      {
        name: 'r/startups',
        fit: 'Startup hiring context',
        note: 'Route founders toward the correct weekly or hiring threads.',
        strictness: 'high',
        badges: ['founder-focused', 'strict-moderation', 'megathread-first'],
        requires: ['Founder context', 'Equity structure if applicable'],
        avoidIf: ['Employer recruiting', 'Non-startup hiring'],
      },
    ],
    tips: ['Define scope', 'Share budget range', 'List required skills'],
    warning: 'Vague hiring posts are commonly removed or ignored.',
    path: 'Intent > Hiring scope > Budget clarity > Community rules',
  },
  {
    id: 'find-cofounders',
    title: 'Find Cofounders',
    description: 'Guide founders toward collaboration paths that fit.',
    marker: 'FC',
    accent: 'from-violet-300/30 via-fuchsia-300/10 to-transparent',
    enabled: true,
    expanded: false,
    communities: [
      {
        name: 'r/cofounder',
        fit: 'Dedicated cofounder discovery',
        note: 'Best for serious founders with a clear equity or role ask.',
        strictness: 'high',
        badges: ['founder-focused', 'strict-moderation'],
        requires: ['Founder experience', 'Equity or role clarity', 'Company stage'],
        avoidIf: ['Employees seeking jobs', 'Employee recruitment', 'Mentorship requests'],
      },
      {
        name: 'r/startups',
        fit: 'Founder discussion and feedback',
        note: 'Good for validating whether the ask belongs in a thread.',
        strictness: 'high',
        badges: ['founder-focused', 'megathread-first'],
        requires: ['Founder context', 'Business background'],
        avoidIf: ['Job postings', 'Generic business advice'],
      },
      {
        name: 'r/indiehackers',
        fit: 'Builders seeking collaborators',
        note: 'Route lightweight collaboration requests here first.',
        strictness: 'low',
        badges: ['beginner-friendly', 'fast-responses'],
        requires: ['Project details', 'Skills needed'],
        avoidIf: ['Formal company structures', 'Investor pitches'],
      },
    ],
    tips: ['Explain traction', 'Define needed role', 'Clarify commitment'],
    warning: 'Equity-only asks need strong context to avoid removal.',
    path: 'Intent > Stage > Cofounder role > Collaboration rules',
  },
  {
    id: 'learn-skills',
    title: 'Learn Skills',
    description: 'Point beginners to learning routes and resources.',
    marker: 'LS',
    accent: 'from-emerald-300/28 via-teal-300/10 to-transparent',
    enabled: true,
    expanded: false,
    communities: [
      {
        name: 'r/learnprogramming',
        fit: 'Beginner-friendly programming help',
        note: 'Best for users asking where to start learning.',
        strictness: 'low',
        badges: ['beginner-friendly', 'learning-safe', 'fast-responses'],
        requires: ['Current experience level'],
        avoidIf: ['Homework dumps without effort', 'Homework with no research attempted'],
      },
      {
        name: 'r/webdev',
        fit: 'Frontend and web project guidance',
        note: 'Route portfolio and project questions carefully.',
        strictness: 'medium',
        badges: ['beginner-friendly', 'learning-safe'],
        requires: ['Project context', 'Technologies involved'],
        avoidIf: ['Pure career questions', 'Hiring requests'],
      },
      {
        name: 'r/cscareerquestions',
        fit: 'Career learning direction',
        note: 'Use only when the question is career-focused.',
        strictness: 'medium',
        badges: ['beginner-friendly', 'learning-safe'],
        requires: ['Career context', 'Experience level'],
        avoidIf: ['Non-career technical questions', 'General advice'],
      },
    ],
    tips: ['Share current level', 'Ask specific questions', 'Avoid homework dumps'],
    warning: 'Broad beginner posts are often redirected to pinned resources.',
    path: 'Intent > Skill level > Goal > Learning resource',
  },
];

export const defaultAnalytics: RouterAnalytics = {
  categoryClicks: {},
  destinationClicks: {},
  recentActivity: [],
  totalCategoryClicks: 0,
  totalDestinationClicks: 0,
  preventedMisroutes: 0,
  reducedRepetitiveQuestions: 0,
  moderationEfficiencyGain: 0,
};
